# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fxtec/pro1x/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    bluetooth \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    multiimgoem \
    qupfw \
    rpm \
    tz \
    uefisecapp \
    xbl \
    xbl_config
